version: "3.6"

services:
  vuenode-fullstack:
    image: vuenode-fullstack
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5050:5050
      - 5051:5051
      - 9229:9229
    ## set your startup file here
    command:
      - npm
      - run
      - dev
